# Generated by Django 5.0.4 on 2024-05-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_pedidos_tamanho_pedidos_tamanho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
