# Generated by Django 5.0.4 on 2024-05-15 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_delete_pedidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tamanho', models.CharField(choices=[('B', 'Broto'), ('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande'), ('F', 'Família')], max_length=1)),
                ('observacao', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Preparo'), ('3', 'Pronto'), ('4', 'Cancelado')], max_length=1, null=True)),
                ('preco', models.FloatField(null=True)),
                ('sabores', models.ManyToManyField(to='pedidos.sabores')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
