# Generated by Django 5.0.7 on 2024-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedidos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
