# Generated by Django 5.0.7 on 2024-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedidos_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='entrega',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True),
        ),
    ]
