# Generated by Django 5.0.7 on 2024-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_pedidos_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='sabores',
            field=models.ManyToManyField(related_name='sabores', to='pedidos.sabores'),
        ),
    ]
